### ISSUE TITLE
clear_button crashes app

### ISSUE THREAD

**Issue by augustgrun** [augustgrun/LiveBluetoothDevice#2]
`2020-02-07 16:47:42.931 883-883/com.augustg.bluetoothservice E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.augustg.bluetoothservice, PID: 883
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter address
        at com.augustg.bluetoothservice.BluetoothViewModel.isConnected(Unknown Source:2)
        at com.augustg.bluetoothservice.databinding.ScanResultItemBindingImpl.executeBindings(ScanResultItemBindingImpl.java:172)
        at androidx.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:472)
        at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:444)
        at androidx.databinding.ViewDataBinding$7.run(ViewDataBinding.java:196)
        at androidx.databinding.ViewDataBinding$8.doFrame(ViewDataBinding.java:290)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
        at android.view.Choreographer.doCallbacks(Choreographer.java:765)
        at android.view.Choreographer.doFrame(Choreographer.java:697)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)`

**Comment by augustgrun** [comment]
May be due to clearing scan results, but individual ViewHolders are still trying to bind to null data

**Comment by augustgrun** [comment]
Rolled back to before adding logic for disconnect_button, issue no longer present

**Comment by augustgrun** [comment]
Solved.
UI logic in view model required non-null "address" parameter to check if connected, but crashed when address became null. Changed parameter to be nullable.
